### ISSUE TITLE
Could you add a license?

### ISSUE THREAD

**Issue by mattcieslak** [ABCD-STUDY/RSI#1]
Hi! Thank you for providing this code. I was wondering if you would be willing to add a license to this repo?

**Comment by RichardWatts** [comment]
Hi Matt -

I thought that I had already selected a license in Github, but maybe not.
What do you suggest? I'm not very familiar with github and licenses!

Thanks -


Richard

**Comment by mattcieslak** [comment]
I usually go with something pretty permissive like MIT or BSD 3-clause. All you'd have to do is add a copy of the license text file into this repo and you're all set

**Comment by mattcieslak** [comment]
thank you!
